# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/talking-machine-learning',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/talking-machine-learning',
                'lib_path': 'talking_machine_learning'},
  'syms': {'talking_machine_learning.core': {'talking_machine_learning.core.foo': ('core.html#foo', 'talking_machine_learning/core.py')}}}
